version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASSWORD: "Jayesslee0604@"  # 密碼修正
      DB_NAME: "alphaTwitter"       # 資料庫名稱修正
      DB_PORT: "3306"
    depends_on:
      - mysql
    networks:
      - default
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Jayesslee0604@"  # 密碼修正
      MYSQL_DATABASE: "alphaTwitter"        # 資料庫名稱修正
    ports:
      - "3307:3306" 
    networks:
      - default
    restart: always

networks:
  default:
    driver: bridge

