name: Deploy to GitHub pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.18.1]

    steps:
      # 檢出專案代碼
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Print directory structure
        run: |
          pwd
          ls -R

      # 設置 Node.js 環境
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}      
      
      - name: Navigate to frontend directory
        working-directory: ./frontend
        run: |
          echo "Navigated to frontend directory"

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm install

      - name: Build project
        working-directory: ./frontend
        run: |
          npm run build


      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        working-directory: ./frontend
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{secrets.DEPLOY_SECRET}}@github.com/${{github.repository}}.git
          npx gh-pages -d dist